# Generated by Django 4.2.3 on 2023-07-31 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comicstore', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comic_name',
            old_name='name',
            new_name='names',
        ),
    ]
