# Generated by Django 4.2.3 on 2023-08-06 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comicstore', '0002_rename_name_comic_name_names'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Book_series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_series_name', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('price', models.IntegerField()),
                ('description', models.TextField()),
                ('cover_type', models.CharField(max_length=200)),
                ('publish_date', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Product_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pages', models.IntegerField()),
                ('height', models.FloatField()),
                ('width', models.FloatField()),
                ('weight', models.FloatField()),
                ('publish_date', models.DateField()),
                ('circulation', models.IntegerField(verbose_name='Тираж')),
                ('age_restrictions', models.IntegerField()),
                ('isbn', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publisher_name', models.CharField(max_length=40)),
            ],
        ),
        migrations.DeleteModel(
            name='comic_name',
        ),
        migrations.AddField(
            model_name='product',
            name='age_restrictions',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='age_restr', to='comicstore.product_details'),
        ),
        migrations.AddField(
            model_name='product',
            name='author_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comicstore.author'),
        ),
        migrations.AddField(
            model_name='product',
            name='book_series_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comicstore.book_series'),
        ),
        migrations.AddField(
            model_name='product',
            name='circulation_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='circulation_id', to='comicstore.product_details'),
        ),
        migrations.AddField(
            model_name='product',
            name='genre_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comicstore.genre'),
        ),
        migrations.AddField(
            model_name='product',
            name='height_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='height_id', to='comicstore.product_details'),
        ),
        migrations.AddField(
            model_name='product',
            name='isbn',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='isbn_name', to='comicstore.product_details'),
        ),
        migrations.AddField(
            model_name='product',
            name='language_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comicstore.language'),
        ),
        migrations.AddField(
            model_name='product',
            name='pages_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pages_id', to='comicstore.product_details'),
        ),
        migrations.AddField(
            model_name='product',
            name='publisher_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comicstore.publisher'),
        ),
        migrations.AddField(
            model_name='product',
            name='weight_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='weight_id', to='comicstore.product_details'),
        ),
        migrations.AddField(
            model_name='product',
            name='width_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='width_id', to='comicstore.product_details'),
        ),
    ]
