# Generated by Django 4.2.3 on 2023-08-08 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comicstore', '0003_author_book_series_genre_language_product_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='author_id',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='book_series_id',
            new_name='book_series',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='circulation_id',
            new_name='circulation',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='genre_id',
            new_name='genre',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='height_id',
            new_name='height',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='language_id',
            new_name='language',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='pages_id',
            new_name='pages',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='publisher_id',
            new_name='publisher',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='weight_id',
            new_name='weight',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='width_id',
            new_name='width',
        ),
    ]
