# Generated by Django 4.2.3 on 2023-08-19 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comicstore', '0004_rename_author_id_product_author_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='age_restrictions',
        ),
        migrations.RemoveField(
            model_name='product',
            name='circulation',
        ),
        migrations.RemoveField(
            model_name='product',
            name='height',
        ),
        migrations.RemoveField(
            model_name='product',
            name='isbn',
        ),
        migrations.RemoveField(
            model_name='product',
            name='pages',
        ),
        migrations.RemoveField(
            model_name='product',
            name='weight',
        ),
        migrations.RemoveField(
            model_name='product',
            name='width',
        ),
        migrations.AddField(
            model_name='product',
            name='prod_details',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='comicstore.product_details'),
            preserve_default=False,
        ),
    ]
