# Generated by Django 4.2.3 on 2023-08-21 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comicstore', '0005_remove_product_age_restrictions_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='publish_date',
        ),
    ]
