# Generated by Django 4.2.3 on 2023-10-04 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comicstore', '0007_alter_product_author_alter_product_book_series_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='languages', to='comicstore.language'),
        ),
    ]
